[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateSet('tag', 'branch')]
    [string] $RefType,

    [Parameter(Mandatory)]
    [string] $RefName,

    [Parameter(Mandatory)]
    [string] $CommitSha,

    [Parameter(Mandatory)]
    [string] $OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$major = 0
$minor = 0
$patch = 0

if ($RefType -eq 'tag') {
    $semVerPattern = '^v(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+(?<build>[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$'
    $match = [regex]::Match($RefName, $semVerPattern)
    if (-not $match.Success) {
        throw "Release tag is not valid SemVer: $RefName"
    }

    if ($match.Groups['prerelease'].Success) {
        foreach ($identifier in $match.Groups['prerelease'].Value.Split('.')) {
            if ($identifier -match '^\d+$' -and $identifier.Length -gt 1 -and $identifier.StartsWith('0')) {
                throw "Release tag has a leading-zero numeric prerelease identifier: $RefName"
            }
        }
    }

    try {
        $major = [uint64] $match.Groups['major'].Value
        $minor = [uint64] $match.Groups['minor'].Value
        $patch = [uint64] $match.Groups['patch'].Value
    } catch {
        throw "Release tag has a numeric component that cannot be represented: $RefName"
    }

    foreach ($component in @($major, $minor, $patch)) {
        if ($component -gt [uint16]::MaxValue) {
            throw "Release tag exceeds the Windows file-version limit of 65535 per component: $RefName"
        }
    }

    $version = $RefName
    $isDev = 'false'
} else {
    if ($CommitSha -notmatch '^[0-9A-Fa-f]{7,64}$') {
        throw "Commit SHA must contain 7 to 64 hexadecimal characters: $CommitSha"
    }
    $version = "v0.0.0-dev+$($CommitSha.Substring(0, 7).ToLowerInvariant())"
    $isDev = 'true'
}

$quad = "$major.$minor.$patch.0"
$content = @'
#Requires AutoHotkey v2.0

; GENERATED BY CI - see scripts/GenerateVersion.ps1
; Built from: __VERSION__

;@Ahk2Exe-SetVersion __FILE_VERSION__
;@Ahk2Exe-SetProductVersion __FILE_VERSION__
;@Ahk2Exe-SetDescription PACS Assistant
;@Ahk2Exe-SetProductName PACS Assistant
;@Ahk2Exe-SetOrigFilename pacs-assistant.exe
;@Ahk2Exe-SetCopyright Copyright (C) 2024-2026 rakan959

class AppVersion {
    static current := "__VERSION__"
    static isDevBuild := __IS_DEV__
}
'@

$content = $content.Replace('__VERSION__', $version)
$content = $content.Replace('__FILE_VERSION__', $quad)
$content = $content.Replace('__IS_DEV__', $isDev)

$fullOutputPath = [IO.Path]::GetFullPath($OutputPath)
$outputDirectory = [IO.Path]::GetDirectoryName($fullOutputPath)
if ([string]::IsNullOrWhiteSpace($outputDirectory) -or -not (Test-Path -LiteralPath $outputDirectory -PathType Container)) {
    throw "Version output directory does not exist: $outputDirectory"
}

[IO.File]::WriteAllText(
    $fullOutputPath,
    $content + [Environment]::NewLine,
    [Text.UTF8Encoding]::new($false)
)

Write-Output "Generated $fullOutputPath for $version"
